global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'portfolio-backend'
    static_configs:
      - targets: ['portfolio-backend-prod:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'portfolio-frontend'
    static_configs:
      - targets: ['portfolio-frontend-prod:80']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['portfolio-postgres-prod:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['portfolio-redis-prod:6379']
    scrape_interval: 30s